### ISSUE TITLE
Future of edge

### ISSUE THREAD

**Issue by RosensRauk** [brenner-tobias/ha-addons-edge#3]
So I tried the edge variant today and it was a smooth ride but not without problems.
It is fully functional but got this from the log: 
"The connection to the origin web server was made, but the origin web server timed out before responding. The likely cause is an overloaded background task, database or application, stressing the resources on your web server. To resolve, please work with your hosting provider or web development team to free up resources for your database or overloaded application."

What is the practical difference between the two versions? 
Speed? 
Features?
Future?

**Comment by brenner-tobias** [comment]
Hi,
thanks for your question. There is not a big difference between the edge and the stable repository, the edge repo includes all commits that we pull into main (so after local dev and testing and a run through our CI pipeline).
We then wait and test until we collected enough new features that are worth a release (we wait at least for a couple of days) and if there is nothing wrong on our end and no complaints from any edge users, we release a new version.

So to answer your question: The edge version might include some new features that are not yet released to stable for a very short time period. It might introduce some bugs or instabilities, that will (hopefully) not make it to stable.

You can always check the [commits in our add-on repository](https://github.com/brenner-tobias/addon-cloudflared/commits/main) and compare to the last version that to see the delta.

Regarding your error: This does not sound like an issue with edge particularly, especially since right now the difference is only two updates to the base-image.

If the error keeps happening, please create an issue in the actual [dev repository](https://github.com/brenner-tobias/addon-cloudflared/issues) and include your logs, config and anything else that might help.

Feel free to let me know if there is anything else.
